version: '3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: itms_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: "itms"
    #      MONGO_INITDB_ROOT_USERNAME: "bs_user"
    #      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - ./src/main/resources/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  postgre:
    image: postgres:latest
    restart: always
    container_name: itms_postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "itms"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./src/main/resources/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

#  svc:
#    restart: always
#    container_name: bus_signalize_svc
#    build: ./
#    expose:
#      - 7000
#    ports:
#      - 7000:7000
##    environment:
##      SPRING_MONGODB_URI: mongodb://bus-signalize-mongodb:27017/bus_signalize
##      SPRING_POSTGRESQL_URL: jdbc:postgresql://bus-signalize-postgresql:5432/bus_signalize

volumes:
  mosquitto_data:
  mosquitto_log: